---
  - name: Adicionando Chave GPG do Docker ContainerD (DEBIAN e Derivados)
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /etc/apt/keyrings/docker.gpg
    when: (ansible_facts['os_family']) == "Debian"

  - name: Verificando arquitetura (DEBIAN e Derivados)
    ansible.builtin.shell: dpkg --print-architecture
    register: architecture
    when: (ansible_facts['os_family']) == "Debian"

  - name: Adicionando Repositorio do Docker ContainerD (DEBIAN e Derivados)
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: docker
    when: (ansible_facts['os_family']) == "Debian"

  - name: Instalar Dependencias (DEBIAN e Derivados)
    ansible.builtin.apt:
      name: 
        - vim
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - gnupg 
        - lsb-release 
        - nfs-common 
        - chrony
      state: present
      update_cache: yes
    when: (ansible_facts['os_family']) == "Debian"

  - name: Instalar Dependências (REDHAT e Derivados)
    ansible.builtin.yum:
      name: 
        - yum-utils
        - vim
        - curl
        - nfs-utils
        - chrony
      state: present
    when: (ansible_facts['os_family']) == "RedHat"

  - name: Adicionar Repositorio (REDHAT e Derivados)
    ansible.builtin.shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    when: (ansible_facts['os_family']) == "RedHat"

  - name: Instalar Containerd
    ansible.builtin.package:
      name: containerd.io
      state: present
      update_cache: yes
  
  - name: Criar o arquivo de configuração do Containerd
    ansible.builtin.shell:
      cmd: containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
  
  - name: Ajuste arquivo Containerd
    ansible.builtin.shell:
      cmd: sudo sed -i 's|SystemdCgroup = false|SystemdCgroup = true|g' /etc/containerd/config.toml

  - name: Habilita Serviço Containerd
    ansible.builtin.systemd:
      name: containerd
      enabled: true