---
  - name: Baixar as imagens do Kubernetes
    ansible.builtin.shell: sudo kubeadm config images pull

  - name: Debug
    ansible.builtin.debug:
      msg: "{{ hostvars['tempcp'].join_clustercp }}"
  
  - name: Associar Control Planes ao Cluster
    ansible.builtin.shell: "{{ hostvars['tempcp'].join_clustercp }}" 
    register: cp

