---
  - name: Adicionando Chave GPG do Kubernetes (DEBIAN e Derivados)
    ansible.builtin.apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      state: present
      keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    when: (ansible_facts['os_family']) == "Debian"

  - name: Adicionando Repositorio do Kubernetes (DEBIAN e Derivados)
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
      state: present
      filename: kubernetes
    when: (ansible_facts['os_family']) == "Debian"

  - name: Adicionar Repositorio do Kubernetes (REDHAT e Derivados)
    ansible.builtin.shell: |
      cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
      EOF
    when: (ansible_facts['os_family']) == "RedHat"

  - name: Criação do Arquivo de Configuração dos Modulos do Kernel para o K8s
    ansible.builtin.file:
      path: /etc/modules-load.d/k8s.conf
      state: touch
      mode: u=rw,g=r,o=r

  - name: Configurar os Modulos do Kernel para o K8s
    ansible.builtin.blockinfile:
      path: /etc/modules-load.d/k8s.conf
      block: |
        overlay
        br_netfilter
        nf_nat
        xt_REDIRECT
        xt_owner
        iptable_nat
        iptable_mangle
        iptable_filter

  - name: Criação do Arquivo de Configuração do Sysctl para o K8s
    ansible.builtin.file:
      path: /etc/sysctl.d/k8s.conf
      state: touch
      mode: u=rw,g=r,o=r

  - name: Mais configuracoes para o Kubernetes
    ansible.builtin.blockinfile:
      path: /etc/sysctl.d/k8s.conf
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1

  - name: Desabiltar o Swap
    ansible.builtin.command: swapoff -a

  - name: Instalar o Kubernetes (DEBIAN e Derivados)
    ansible.builtin.apt:
      name:
      - kubelet
      - kubeadm
      - kubectl
      state: present
    when: (ansible_facts['os_family']) == "Debian"

  - name: Instalar o Kubernetes (REDHAT e Derivados)
    ansible.builtin.yum:
      name:
      - kubelet
      - kubeadm
      - kubectl
      state: present
      disable_excludes: "kubernetes"
    when: (ansible_facts['os_family']) == "RedHat"

  - name: Instalar o Helm
    ansible.builtin.shell: curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    ignore_errors: true

  - name: Atalho do executavel do Helm 
    ansible.builtin.shell: ln -s /usr/local/bin/helm /usr/bin/helm
    ignore_errors: true

  - name: Habilita Serviço Kubelet
    ansible.builtin.systemd:
      name: kubelet
      enabled: true

  - name: Reboot
    ansible.builtin.reboot: 
      reboot_timeout: 120

  - name: Resetar Regras de Firewall
    ansible.builtin.shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
